use_frameworks!

platform :ios, '9.0'

target 'PlaceholderTextView_Example' do
  pod 'UDPlaceholderTextView', :path => '../'

  target 'PlaceholderTextView_Tests' do
    inherit! :search_paths

    
  end
end
